version: "2"
volumes:
  pgdata:
  cache:
services:
  postgres:
    image: "openmaptiles/postgis:2.3"
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
     - "5432"
    env_file: .env
  import-natural-earth:
    image: "openmaptiles/import-natural-earth:1.2"
    env_file: .env
    links:
    - postgres
  import-water:
    image: "openmaptiles/import-water:0.2"
    env_file: .env
    links:
    - postgres
  import-lakelines:
    image: "openmaptiles/import-lakelines:0.9"
    env_file: .env
    links:
    - postgres
  import-osm:
    image: "openmaptiles/import-osm:0.3"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    links:
    - postgres
    volumes:
     - ./data:/import
     - ./build:/mapping
     - cache:/cache
  import-osmborder:
    image: "openmaptiles/import-osmborder:0.2"
    env_file: .env
    links:
    - postgres
  import-osm-diff:
    image: "openmaptiles/import-osm:latest"
    env_file: .env
    command: ./import_diff.sh
    environment:
      DIFF_MODE: ${DIFF_MODE}
    links:
    - postgres
    volumes:
     - ./data:/import
     - ./build:/mapping
     - cache:/cache
  update-osm:
    image: "openmaptiles/import-osm:latest"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    command: ./import_update.sh
    links:
    - postgres
    volumes:
     - ./data:/import
     - ./build:/mapping
     - cache:/cache
  import-sql:
    image: "openmaptiles/import-sql:0.1"
    env_file: .env
    links:
    - postgres
    volumes:
     - ./build:/sql
  openmaptiles-tools:
    image: "openmaptiles/openmaptiles-tools:latest"
    env_file: .env
    links:
    - postgres
    volumes:
     - .:/tileset
     - ./build:/sql
  mapbox-studio:
    image: "osm2vectortiles/mapbox-studio"
    volumes:
     - ./build/openmaptiles.tm2source:/projects/openmaptiles.tm2source
    links:
     - postgres:db
    ports:
     - "3000:3000"
  generate-changed-vectortiles:
    image: "openmaptiles/generate-vectortiles:0.1"
    command: ./export-list.sh
    volumes:
    - ./data:/export
    - ./build/openmaptiles.tm2source:/tm2source
    links:
    - postgres:postgres
    env_file: .env
  generate-vectortiles:
    image: "tnris/tilestache" # 52.55 13.28 52.46 13.51
    command:  "bash -c 'python ./application.wsgi && tilestache-seed.py --config /var/tilestache/tilestache-cfg-rendered.cfg --layer playground_point --bbox 55 6 48 16 --output-directory /export --extension=geojson 8'"
    volumes:
      - ./tilestache.cfg:/var/tilestache/tilestache.cfg:ro
      - ./data:/export
    links:
    - postgres:postgres
    env_file: .env
    environment:
      #BBOX: "8.25,46.97,9.58,47.52"
      BBOX: "9.84 53.4 10 53.6"
      #BBOX: ${BBOX}
      MIN_ZOOM: 1 #${MIN_ZOOM}
      MAX_ZOOM: 4 #${MAX_ZOOM}
  tilestash:
    image: "tnris/tilestache"
    volumes:
      - ./tilestache.cfg:/var/tilestache/tilestache.cfg:ro
    links:
    - postgres:postgres
    env_file: .env
    ports:
      - "8080:8080"
